Send ocr processing messages to active mq
slub/ocrd_manager pull request #60
Opened 2023-05-16 16:02 UTC by markusweigelt

- add functions to send task action messages to `ocrd_lib.sh`
- update activemq client
- use process function to set task from `OPEN` state to `INWORK`
- use close function to close task over task action message queue

![comments_popup_with_ocrd_messages](https://github.com/slub/ocrd_manager/assets/3832618/0abab3ac-b579-4252-a6fd-4ca87296690f)

(Depends on [this Kitodo.Production extension](https://github.com/kitodo/kitodo-production/pull/5657) for task action messages.)

2023-05-17 11:03 UTC, bertsky requested changes
Very nice!

I see a couple of points that still need to be addressed:
1. the ERR trap currently only logs locally, but should now also be used to signal via MQ; I suggest adding a line to `logerr` which uses `kitodo_production_task_action_error_open` with a suitable custom message (involving `$BASH_COMMAND` and/or `$(caller)` to be as concrete as possible)
2. in case the Kitodo side does not have the right version installed, shouldn't we fall back to the old `KitodoProduction.FinalizeStep.Queue` interface?
3. we must make sure that if no Kitodo is configured, then also `ACTIVEMQ` stays empty. Currently it will read `:` and fail. So either catch that specifically, or avoid just setting `$MQ_HOST:$MQ_PORT` in docker-compose.yml

2023-05-22 14:11 UTC, markusweigelt commented
> Very nice!
> 
> I see a couple of points that still need to be addressed:
> 
> 1. the ERR trap currently only logs locally, but should now also be used to signal via MQ; I suggest adding a line to `logerr` which uses `kitodo_production_task_action_error_open` with a suitable custom message (involving `$BASH_COMMAND` and/or `$(caller)` to be as concrete as possible)

For Kitodo I suggest to prevent detailed messages. I think the user should only be informed that a problem occurs and get more information in the monitor to fix the problem.

> 2. in case the Kitodo side does not have the right version installed, shouldn't we fall back to the old `KitodoProduction.FinalizeStep.Queue` interface?

Currently, I am not sure how we can find out. Do we provide another enviroment variable with which to pass the Version of Kitodo? Or do we expect the Kitodo Version as a parameter to the Kitodo script.

> 3. we must make sure that if no Kitodo is configured, then also `ACTIVEMQ` stays empty. Currently it will read `:` and fail. So either catch that specifically, or avoid just setting `$MQ_HOST:$MQ_PORT` in docker-compose.yml

Good point i will change this.

2023-05-23 07:46 UTC, bertsky commented
> For Kitodo I suggest to prevent detailed messages. I think the user should only be informed that a problem occurs and get more information in the monitor to fix the problem.

Yes, the details are already in the OCRD logs that can be viewed in the Monitor. We could also just use your default message – but we must add the signal.

> Do we provide another enviroment variable with which to pass the version of Kitodo? Or do we expect the Kitodo version as a parameter to the Kitodo script. Alternatively maybe a flag but we can not introduce flags for every case.

IIRC there are a couple of variables available from Kitodo scripts – if the version is among them, that would be the cleanest solution. (We already have an `ENV ACTIVEMQ_CLIENT` – we could add a runtime variable `ACTIVEMQ_PROTOCOL` for example.)

> Good point i will change this.

In the simplest case, just add another `test "$ACTIVEMQ" != :`

2023-06-07 15:16 UTC, markusweigelt commented
Changed the implemenation with your hints from review. Now you can configure the queue over env variable and if no variable is set the default queue is used.

2023-06-07 15:45 UTC, bertsky commented on ocrd_lib.sh
>        ;;
I suggest sticking with our usual error logging. Instead of the echo, do

    logger -p user.error -t $TASK "Unknown task action type"

2023-06-07 15:45 UTC, bertsky commented on ocrd_lib.sh
> +  if test -n "$ACTIVEMQ" -a "$ACTIVEMQ" != ":" -a -n "$TASK_ID"; then
Are you sure you want to allow passing an empty `$ACTION` here? (Don't know your client well enough, some programs can cope with empty CLI arguments.)

If not, I suggest keeping the extra condition (so nothing is attempted to send):

```suggestion
  if test -n "$ACTIVEMQ" -a "$ACTIVEMQ" != ":" -a -n "$TASK_ID" -a -n "$ACTION"; then
```

2023-06-07 15:45 UTC, bertsky commented on ocrd_lib.sh
> +  if test -n "$ACTIVEMQ" -a "$ACTIVEMQ" != ":" -a -n "$TASK_ID"; then
Also, what happened to the older protocol where we used to send PROCESS_ID as message?

2023-06-07 15:45 UTC, bertsky commented on process_images.sh
> + ACTIVEMQ_QUEUE: Queue to handle result callback. Choose between default "FinalizeTaskQueue" or "TaskActionQueue" (optional)
```suggestion
 ACTIVEMQ_QUEUE: Protocol type handling result callbacks. Choose between "FinalizeTaskQueue" (default) or "TaskActionQueue" (optional)
```

2023-06-07 15:47 UTC, bertsky approved these changes

2023-06-07 15:49 UTC, bertsky commented
> [bertsky](https://github.com/bertsky) approved these changes [now](https://github.com/slub/ocrd_manager/pull/60#pullrequestreview-1468041851)

strange that GH sees it this way, although it **knows** that that review only applied to the last commit (view changes since...)

2023-06-07 16:03 UTC, bertsky approved these changes
Thx!

2023-06-08 08:17 UTC, merged